In [1]:
import numpy as np

In [7]:
ls1 = [1,3,5]
arr1= np.array(ls1)
print (arr1)

[1 3 5]


In [15]:
ls1 = [1,3,5]
ls1.sort()
ls1


[1, 3, 5]

In [16]:
arr1.sort()
arr1

array([1, 3, 5])

In [17]:
len(ls1)

3

In [18]:
len(arr1)

3

In [19]:
x = sum(ls1)
x

9

In [21]:
y = sum(arr1)
y

9

In [5]:
ls1 = [1,3,5]
ls1

[1, 3, 5]

In [6]:
from statistics import mean
ml=mean(ls1)
ml

3

In [8]:
arr1= np.array(ls1)
arr1

array([1, 3, 5])

In [9]:
a1=arr1.mean()
a1

3.0

In [10]:
arr1

array([1, 3, 5])

In [11]:
arr1.ndim

1

In [13]:
a1= mean(arr1)
a1

3

In [14]:
##Multidimension Array

In [50]:
ls2=[[23,np.nan,453,87,2,3,],[34,78,np.nan,43,46,24],[56,np.nan,94,4,43,40]]
ls2

[[23, nan, 453, 87, 2, 3], [34, 78, nan, 43, 46, 24], [56, nan, 94, 4, 43, 40]]

In [46]:
print(type(np.nan))

<class 'float'>


In [48]:
print(ls2[1][1])

78


In [51]:
arr2= np.array(ls2)
arr2

array([[ 23.,  nan, 453.,  87.,   2.,   3.],
       [ 34.,  78.,  nan,  43.,  46.,  24.],
       [ 56.,  nan,  94.,   4.,  43.,  40.]])

In [44]:
arr2.shape

(3, 6)

In [39]:
arr2.ndim

2

In [45]:
arr2.dtype

dtype('float64')

In [52]:
arr3 =arr2
arr3

array([[ 23.,  nan, 453.,  87.,   2.,   3.],
       [ 34.,  78.,  nan,  43.,  46.,  24.],
       [ 56.,  nan,  94.,   4.,  43.,  40.]])

In [54]:
arr2m = arr2.mean()
arr2m

nan

In [55]:
ls5 = [[23,89,453,87,2,3,],[34,78,55,43,46,24],[56,98,94,4,43,40]]

In [56]:
arr5 =np.array(ls5)
arr5

array([[ 23,  89, 453,  87,   2,   3],
       [ 34,  78,  55,  43,  46,  24],
       [ 56,  98,  94,   4,  43,  40]])

In [57]:
arr5m = arr5.mean()
arr5m

70.66666666666667

In [60]:
arr2max = np.nanmax(arr2)
arr2max

453.0

In [62]:
arr2min = np.nanmin(arr2)
arr2min

2.0

In [63]:
arr2m = np.nanmean(arr2)
arr2m

68.66666666666667

In [64]:
arr2.shape

(3, 6)

In [73]:
m1 = np.nanmean(arr2,axis=1)
m1

array([113.6,  45. ,  47.4])

In [75]:
np.isnan(arr2)

array([[False,  True, False, False, False, False],
       [False, False,  True, False, False, False],
       [False,  True, False, False, False, False]])

In [7]:
import numpy as np
a=np.array([(17,12,np.nan,3),(30,np.nan,44,59),(78,34,98,12),(22,np.nan,78,np.nan)])
a

array([[17., 12., nan,  3.],
       [30., nan, 44., 59.],
       [78., 34., 98., 12.],
       [22., nan, 78., nan]])

In [9]:
b= a
b= np.copy(a)
b

array([[17., 12., nan,  3.],
       [30., nan, 44., 59.],
       [78., 34., 98., 12.],
       [22., nan, 78., nan]])

In [15]:

import numpy as np
a=np.array([(17,12,np.nan,3),(30,np.nan,44,59),(78,34,98,12),(22,np.nan,78,np.nan)])
a[np.isnan(a)]=0
a

array([[17., 12.,  0.,  3.],
       [30.,  0., 44., 59.],
       [78., 34., 98., 12.],
       [22.,  0., 78.,  0.]])

In [18]:
b1= np.nanmean(b)
b1

40.583333333333336

In [21]:
b[np.isnan(b)]=b1
b

array([[17.        , 12.        , 40.58333333,  3.        ],
       [30.        , 40.58333333, 44.        , 59.        ],
       [78.        , 34.        , 98.        , 12.        ],
       [22.        , 40.58333333, 78.        , 40.58333333]])

SyntaxError: can't assign to function call (<ipython-input-85-fda174be4903>, line 1)